# Generated by Django 4.1.2 on 2022-10-12 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_auto', models.CharField(max_length=100)),
                ('brand_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.brandauto')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('auto_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.color')),
                ('auto_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.modelauto')),
            ],
        ),
    ]
