# Generated by Django 4.1.2 on 2022-10-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelauto',
            name='brand_auto',
        ),
        migrations.AddField(
            model_name='orderbuy',
            name='auto_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.brandauto'),
        ),
    ]
