# Generated by Django 4.1.2 on 2022-10-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_modelauto_brand_auto_orderbuy_auto_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbuy',
            name='auto_brand',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sales.brandauto'),
        ),
    ]
