# Generated by Django 4.1.2 on 2022-10-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_orderbuy_auto_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbuy',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderbuy',
            name='auto_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.brandauto'),
        ),
    ]
