# Generated by Django 4.1.2 on 2022-10-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_orderbuy_amount_alter_orderbuy_auto_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelauto',
            name='brand_auto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.brandauto'),
        ),
    ]
